// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fieldWarning': string;
  'root': string;
  'userConfigRoot': string;
}
export const cssExports: CssExports;
export default cssExports;
